export enum CertificateWithdrawnReason {
    
    COMPROMISED_PRIVATE_KEY = 'COMPROMISED_PRIVATE_KEY',
    CERTIFICATE_AUTHORITY_COMPROMISED = 'CERTIFICATE_AUTHORITY_COMPROMISED',
    CERTIFICATE_MISUSE = 'CERTIFICATE_MISUSE',
    EXPIRATION = 'EXPIRATION',
    CHANGE_OF_OWNERSHIP = 'CHANGE_OF_OWNERSHIP',
    INCORRECT_INFORMATION = 'INCORRECT_INFORMATION',
    SUSPECTED_FRAUD_OR_ABUSE = 'SUSPECTED_FRAUD_OR_ABUSE',
    UNSPECIFIED = 'UNSPECIFIED',

}