export enum ExtendedKeyUsage {
    
    TSL_WEB_SERVER_AUTHENTICATION = 'TSL_WEB_SERVER_AUTHENTICATION', 
    TLS_WEB_CLIENT_AUTHENTICATION = 'TLS_WEB_CLIENT_AUTHENTICATION' ,
    SIGN_EXECUTABLE_CODE = 'SIGN_EXECUTABLE_CODE' ,
    EMAIL_PROTECTION = 'EMAIL_PROTECTION',
    IPSEC_END_SYSTEM = 'IPSEC_END_SYSTEM',
    IPSEC_TUNNEL = 'IPSEC_TUNNEL',
    IPSEC_USER = 'IPSEC_USER',
    TIMESTAMPING = 'TIMESTAMPING',
    OCSP_SIGNING = 'OCSP_SIGNING'

}